name: Lint Code Base

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint Code Base
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
